name: Build Docker Image for Docker Desktop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Docker using the official installation script
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          docker --version

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-docker-image:latest .

      # # Save the Docker image as a tar file
      # - name: Save Docker image as tar file
      #   run: |
      #     docker save -o my-docker-image.tar my-docker-image:latest

      # # Upload the tar file as an artifact for download
      # - name: Upload Docker image artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: docker-image
      #     path: my-docker-image.tar
